### ISSUE TITLE
Timing advance when network is changed from wifi to mobile data

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [christianrowlands/android-network-survey#11]
Hi Christian,

I am developing an Android app to read Timing advance of LTE. Whenever device is on wifi, TA always coming as invalid as expected. But when i turn off wifi and connect to mobile data still it is coming as invalid. If i restart device then TA coming as valid value. Is the device restart requires for switching to mobile data to read proper TA?

And sometimes TA coming as invalid on mobile data. Is this expected? What are the ways to get valid TA always on mobile datA?

The api used to read TA is cellSignalStrength.timingAdvance

Thanks in advance

**Comment by christianrowlands** [comment]
I have not seen where I have to restart the device to get TA to come in. It has been pretty reliable for me on all the phones I use, including both Samsung and Pixel phones. 

One thing to note is that you won't be able to get TA for CDMA or UMTS technologies, only for GSM and LTE... and really, I have never seen it for GSM on my phones, mainly because I don't really have any GSM towers left around me. But on LTE, I see it really reliably.

All that being said, you will only see the TA when there is an active session with the tower. This is because to calculate the TA, the phone actually has to transmit to the tower and the tower has to tell the phone how delayed the signal is. This is why TA won't come in over Wi-Fi. My solution for keeping the TA value present when not on Wi-Fi, I send a ping to 8.8.8.8 every 10 seconds. This forces the phone to open a data session, and for the phone to transmit it needs to know what TA to use.

**Comment by bhuvaneshwariarkala** [comment]
Hi Christian,

Even  I am sending a ping to 8.8.8.8 for every 10 seconds, still I don't see valid TA when I switch from wifi to mobile data in my application. Where as this is working with your application. Thats the reason I want to know if anything extra you are doing to get valid TA on this switch from wifi to mobile
