### ISSUE TITLE
[Feature Request] add band number

### ISSUE THREAD

**Issue by davidbtc2009** [christianrowlands/android-network-survey#15]
First off i would like to say this is a FANTASTIC app. Could you add the connected band number such as B2, B66, etc when connected to LTE and N41, N71, etc when in 5G? Either that or an EARFCN to band calculator?

**Comment by christianrowlands** [comment]
@davidbtc2009 , thank you for the compliment and also for the feature request! I think that is a great idea because I can never remember what EARFNCs fall in each band either.

Do you think it would be ok to throw it in parenthesis next to the EARFCN similar to how I threw the SSS and PSS next to the PCI?

I will work something up and post a screenshot when I get a chance.

**Comment by davidbtc2009** [comment]
@christianrowlands that might be okay, but as a screen reader user it might be an issue. My thought is try it and we can see how it goes

**Comment by christianrowlands** [comment]
Let me know if you have other ideas on how to lay it out. Otherwise I will play around with it and see what I come up with.

**Comment by shortwavesurfer2009** [comment]
Status of this?

**Comment by christianrowlands** [comment]
I was hoping to have this done by now, but got side tracked on other projects. It is still on my radar and I will hopefully be getting to it soon.

Thanks for pinging this ticket.

**Comment by christianrowlands** [comment]
@davidbtc2009 and @shortwavesurfer2009 , I got around to adding this feature (sorry it took so long).

Here is a screenshot where I added the band number next to the EARFCN. I still need to work up a solution for 5G, but that should be straightforward. Do you think the UI is clear?

![image](https://github.com/christianrowlands/android-network-survey/assets/8020686/215ae49a-c549-427b-9d39-4703c9d7cc84)

**Comment by davidbtc2009** [comment]
Perfect.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by christianrowlands** [comment]
It turns out 5G NR was not as easy as I wanted it to be. There are small overlaps in the band nrafrcns. For example, `376000` is in both n3 and n39 (See screenshot below). I do see that n3 is FDD and n39 is TDD, but I am not seeing a way in the Android API to know if the nrarfcn I have is associated with FDD or TDD.

I do see that Android has an API method https://developer.android.com/reference/android/telephony/CellIdentityNr#getBands() . I have not seen it be populated yet, but I am going to try driving around with a couple different phones to see if I can hit an area where that method returns something useful.

<img width="771" alt="image" src="https://github.com/christianrowlands/android-network-survey/assets/8020686/2222e796-71c3-4aad-b66b-9e7161bec40a">

**Comment by christianrowlands** [comment]
I have driven around a bunch and never saw it populated, but I wired it up to the UI anyway (I like to gamble 😄 ). If anyone has real 5G in their area (not the fake 5G that service providers do when they put the 5G icon on the phone's toolbar but the phone is really using LTE), let me know what you see in the `NARFCN/band` section of the Cellular UI. I am going to close this issue for now but reopen it if you see anything wrong with the 5G NR band.
