### ISSUE TITLE
View the passwords of the connected wifi networks [with root]

### ISSUE THREAD

**Issue by GuiSousa135** [christianrowlands/android-network-survey#22]
would be very good the functionality of identifying the wifi network passwords that are connected in android, using the root permission to read and show to the user.

**Comment by christianrowlands** [comment]
@GuiSousa135 Thank you for the suggestion. I really appreciate it!

That does sound like a cool feature addition to Network Survey. However, I am worried about the security implications of implementing such a feature. I consider your personal WiFi passwords very sensitive, and I would hate to accidentally expose them. For example, if they are being displayed in the app and someone looks over your shoulder or the user takes and shares a screenshot without realizing their passwords are visible.

And since viewing the saved WiFi password is pretty [straightforward on Android now](https://www.androidpolice.com/how-to-see-android-wifi-password/), I think it is best to leave it to the OS to handle that. 

However, if you have a more specific use case in mind that I am not understanding add a comment in this ticket and we can keep brainstorming on what this password feature might entail.

**Comment by GuiSousa135** [comment]
I think it would be a very useful function in Network Survey to make it more complete and powerful, it would be a very welcome possibility, whether for sharing (in case of forgetting, for example) as well as for later verifications (pentests, password strength ). As for the issue of security, I think it is an important point to take into account, but let's consider that the user who has root access on the phone is already an advanced user, with knowledge about android, thus having greater responsibility for their kept passwords on mobile, while users who choose not to use this function can deny root access to the app, and users without root access will not have access. So I think the ability to see the passwords of wifi networks already connected would be very positive.

**Comment by christianrowlands** [comment]
Yeah, that is a good point. Any user running on root likely has enough knowledge to be careful with passwords. Let me see how hard it will be to get the passwords with root. Based on a Google search it seems like I only need to read a file on the device.

**Comment by GuiSousa135** [comment]
Very good, I'm not a developer, but from what I've been researching, applying this function is relatively simple for rooted users, after authorization by the root Manager, just read an internal file with a list of repasswords. I don't know if this works to very customized systems (OneUIMiUI), but on stock Android it's something simple.

**Comment by christianrowlands** [comment]
Thanks for the bump on this. I add a reminder to look at it this week.

**Comment by christianrowlands** [comment]
Hey @GuiSousa135 . After looking into this more, you are correct, it is relatively simple to get access to them for a rooted user. However, after thinking about this more and weighing the pros and cons, at this time I don't want to add this feature to Network Survey. I appreciate you taking the time to submit the request, and I apologize it has taken me so long to make a decision on this. Feel free to keep submitting feature requests, and I will try to run through them a bit faster in the future 😉 .
