### ISSUE TITLE
Add a map of cellular base stations

### ISSUE THREAD

**Issue by Korb** [christianrowlands/android-network-survey#33]
This would be convenient for finding out the reasons for poor communication in dense urban areas, and choosing another cellular operator in cases where the location of its base stations is more favorable. Of course, the current base station should be specially marked on the map, just as the icons of all base stations visible on the air should be equipped with an indication of signal strength.

There are open databases of cellular base stations with API. You can use one of them.

**Comment by christianrowlands** [comment]
Thank you for the suggestion. I think this would be a great feature! I will look into those open databases and see what I need to do to start getting access to the data.

**Comment by pm4rcin** [comment]
Not sure if it's of any use to this project but there's excellent data of BTSes for Poland. https://beta.btsearch.pl/

**Comment by christianrowlands** [comment]
Nice, thanks for sharing the link. I will see if that site allows me to export the data

I am pretty close to having this working, at least in a basic form.

**Comment by pm4rcin** [comment]
It is possible to export from this link: https://beta.btsearch.pl/bts/export
Note that it has to be exported for every operator manually from what I can tell (PLUS, T-Mobile, Orange, PLAY). Also note that there's something called NetWorks! which is basically a collaboration of T-Mobile and Orange but I can't recall any time having it displayed as separate MNC but only either T-mobile or Orange.

**Comment by christianrowlands** [comment]
Ok, I added the tower map view and am working on building and testing the release now. Hopefully can push this out in the next day or two.

I went with the open street maps osmdroid library, which is not the best. I took this approach because MapBox and others perform too much tracking. My first implementation with MapBox looked really nice, and I could not get osmdroid to look the same way... but at least it is working.

This first pass is really basic. I plan to add future improvements such as showing a line to the current serving cell.

Take a look and let me know if anything jumps out at you as far as bugs or suggestions for future improvements. Keep in mind this is a basic first pass though, it is nothing fancy.

**Comment by christianrowlands** [comment]
Version 1.25 has been released with this map feature. Again, keep in mind it is basic... and the maps are ugly.. so let me know what improvements you would like to see.

🍻

**Comment by pm4rcin** [comment]
I thought that towers will be placed on map but from what I can see it's just measurements. It's obviously not your fault it's just first time for me seeing the data from OpenCellID. But as I said above if you could integrate data from btsearch then at least poland would have (almost) perfect data.

**Comment by christianrowlands** [comment]
It is the towers that are placed on the map, but if there is only one measurement for the tower then it will display the tower location on the single measurement. Probably not ideal, but it seems to be the way that OpenCelliD works.

I will see about using the data from btsearch.

FWIW, I did not have great OpenCelliD data around my main areas as well, so I used the Tower Collector app for OpenCelliD to submit survey data. I am also considering having Network Survey be able to submit data to OpenCelliD, but that will take some time to flush out.

**Comment by christianrowlands** [comment]
@pm4rcin , I looked at the format, and the records don't have the radio technology associated with the tower. When playing with the OpenCelliD data, I found that there were times where the same MCC/MNC/LAC/CID was used for two different radio technologies (e.g. UMTS and LTE). Maybe this is an error in the data, but either way it caused me to make the database record uniqueness on Radio+MCC+MNC+LAC+CID. Since the data at BTSearch does not have the radio technology I don't know how to update the existing records from OpenCellid, and there would be problems with the code in the mobile app because I allow the user to filter on radio tech to keep the display clean.

Here is an example record from BTSearch:

```
26002;00010;57751;00000;50.838333;17.278889;-1;Oleśnica Mała - gm. Oława, wieża P4 Play niedaleko A4 [DLN:84981:L800];0
```

Do you have any thoughts on this? Any suggestions on how you would want this handled?

**Comment by pm4rcin** [comment]
There's better link, it has data in csv with everything https://btsearch.pl/export.php

EDIT: If you look with your map at this data and data from OpenCellID you'll notice immediately how much different it is. BTSearch has precise data with exact coordinates while OCID has somewhat accurate but far from perfect.

**Comment by christianrowlands** [comment]
Thank you for that link, it is very helpful. It looks like it has everything I need. I will have to do some data mapping, such as mapping the text network name to the PLMN (T-Mobile to 26002) and the location to decimal degrees, but that should be pretty straightforward.

I will need to think through how I am going to handle the upserts since you are indicating that the BTSearch data is more accurate. I don't want the automated daily OpenCelliD import that I wrote to overwrite this data, so I need to figure out the best way to handle that.

I will let you know when I have it all coded up and it is ready to try.

**Comment by christianrowlands** [comment]
Ok, I imported those towers, you should be able to see them now.

Next I need to update the display dialog for the towers to display something different for the BTSearch towers. I also need to fix the slow map when there are a lot of towers, but for now you should be able to see the towers.

**Comment by Korb** [comment]
> christianrowlands closed this as completed on Jun 15

🤔😉

**Comment by christianrowlands** [comment]
Solid point @Korb . I will open a new issue for any other changes. Or @pm4rcin , if you have any other thoughts a GitHub discussion would be a good place for that as well.  https://github.com/christianrowlands/android-network-survey/discussions
